Repository UnBArqDsw2025-2-Turma02/2025.2_T02_G6_AquiTemFCTE_Entrega_01, pull requests merged in 2025-09, with the labels that each got.

#10 docs: adiciona topico topico de ishikawa em artefatos generalistas
  .github/pull_request_template.md
  docs/Base/1.1.1.Mapping.md
  docs/Base/1.1.2.Sketch.md
  docs/Base/1.1.3.Decide.md
  docs/Base/1.1.4.Prototype.md
  docs/Base/1.1.5.Test.md
  docs/Base/1.1.DesignSprint.md
  docs/Base/1.2.2.DiagramaIshikawa.md
  docs/Base/1.4.ParticipacoesBase.md
  docs/_sidebar.md
  docs/assets/diagramaIshikawa/DiagramaIshikawaLucas.jpg
Labels: documentation

#14 feat(docs): add ata 01
  docs/Base/2.1.1.Ata01.md
  docs/_sidebar.md
Labels: documentation

#12 feat(docs): add rich picture to sketch and artifacts sessions
  docs/Base/1.1.2.Sketch.md
  docs/Base/1.2.3.RichPicture.md
  docs/_sidebar.md
Labels: documentation

#16 Docs: adiciona tópico extra de disponibilidade do time
  docs/Extra/1.5.2.DisponibilidadeDaEquipe.md
  docs/Extra/image.png
  docs/_sidebar.md
  docs/assets/extra/DisponibilidadeEquipe-heatmap-geral.jpg
  docs/assets/extra/DisponibilidadeIndividual.jpg
Labels: documentation

#15 docs: adição do léxico aos artefatos generalistas
  docs/Base/1.1.2.Sketch.md
  docs/Base/1.2.5.Léxico.md
  docs/_sidebar.md
Labels: documentation

#19 docs(bpmn): adiciona bpmn kanban e texto do tópico 1.3 BPMN
  .husky/prepare-commit-msg
  docs/Base/1.3.1.BPMNKanban.md
  docs/Base/1.3.ModelagemBPMN.md
  docs/_sidebar.md
  docs/assets/AquiTemFCTE_BPMN_Kanban_Caio_Isaque.jpg
Labels: documentation

#18 docs: corrige as imagens do 5W2H
  docs/Base/1.1.2.Sketch.md
  docs/Base/1.2.4.5W2H.md
  docs/assets/AqDsSw5W2H.jpg
Labels: bug

#22 docs: adiciona ata da segunda reuniao
  docs/Base/2.1.Ata01.md
  docs/Base/2.2.Ata02.md
  docs/_sidebar.md
Labels: documentation

#27 docs: corrige imagem do 5w2h
  docs/Base/1.1.2.Sketch.md
  docs/Base/1.2.4.5W2H.md
Labels: bug, documentation

#28 DOCS/ Design Sprint Mapping
  docs/Base/1.1.1.Mapping.md
  docs/assets/extra/Core.png
  docs/assets/extra/Map.png
  docs/assets/extra/MetasMetricasRiscos.png
Labels: documentation

#30 DOCS/Adiciona BPMN do Scrum e Documentação
  docs/Base/1.3.2.BPMNScrum.md
  docs/Base/1.3.ModelagemBPMN.md
  docs/_sidebar.md
  docs/assets/extra/BPMN_Scrum.svg
Labels: documentation

#31 docs: adiciona tópico "1.1.3.Decide"
  docs/Base/1.1.3.Decide.md
  docs/Base/1.3.3.BPMNSoftware.md
  docs/_sidebar.md
  docs/assets/485914823-4fe3ee4e-a066-48e7-a447-2973840fccc8.png
  docs/assets/AquiTemFCTE_StoryBoardFlow.jpg
Labels: documentation

#41 docs(backlog e marca): corrige erro de ortografia
  docs/Base/1.1.3.Decide.md
  docs/Extra/1.5.3.BacklogDoProduto.md
  docs/Extra/1.5.4.MarcaAquiTemFCTE.md
Labels: bug, documentation

#43 Docs/participacoes base
  docs/Base/1.4.ParticipacoesBase.md
Labels: documentation

#42 Docs/Adiciona BPMN do Software e Documentação
  docs/Base/1.3.3.BPMNSoftware.md
  docs/Base/1.3.ModelagemBPMN.md
  docs/_sidebar.md
  docs/assets/bpmn/BPMNSoftware-autenticacao.jpg
  docs/assets/bpmn/BPMNSoftware-compra-troca.jpg
  docs/assets/bpmn/BPMNSoftware-geral.jpg
  docs/assets/bpmn/BPMNSoftware-perfil.jpg
  docs/assets/favicon.png
Labels: documentation

#45 docs: corrige erros de merge da main
  docs/Base/1.4.ParticipacoesBase.md
  docs/Base/1.5.IniciativasExtras.md
  docs/Base/1.Base.md
Labels: documentation

#46 docs: corrige caminhos da imagens
  docs/Base/1.1.4.Prototype.md
Labels: bug, documentation
